.DELETE_ON_ERROR:

ROM = dkl2-savestate-patched.gb

BUILD_DIR = build
GFX_DIR = gfx

NAME = dkl2-practice
SOURCE_FILE = $(NAME).asm
GENERATE_MENU = generate-menu.py
MENU_TXT = menu.txt

VERSION = $(GFX_DIR)/version.2bpp
CURSOR = $(GFX_DIR)/cursor.2bpp
IMAGES = $(VERSION) $(CURSOR)

ASFLAGS_STD = -D FRAMECOUNTER=0 -D LAGCOUNTER=0
LDFLAGS_STD = -O $(ROM) -n $(SYMBOL_FILE_STD)
OBJECT_FILE_STD = $(NAME).o
OUTPUT_ROM_STD = $(NAME).gb
SYMBOL_FILE_STD = $(NAME).sym
STD_OBJECTS = $(OBJECT_FILE_STD) $(OUTPUT_ROM_STD) $(SYMBOL_FILE_STD)

NAME_FRAMES = $(NAME)-frames
ASFLAGS_FRAMES = -D FRAMECOUNTER=1 -D LAGCOUNTER=0
LDFLAGS_FRAMES = -O $(ROM) -n $(SYMBOL_FILE_FRAMES)
OBJECT_FILE_FRAMES = $(NAME_FRAMES).o
OUTPUT_ROM_FRAMES = $(NAME_FRAMES).gb
SYMBOL_FILE_FRAMES = $(NAME_FRAMES).sym
FRAMES_OBJECTS = $(OBJECT_FILE_FRAMES) $(OUTPUT_ROM_FRAMES) $(SYMBOL_FILE_FRAMES)

NAME_LAG = $(NAME)-lag
ASFLAGS_LAG = -D FRAMECOUNTER=1 -D LAGCOUNTER=0
LDFLAGS_LAG = -O $(ROM) -n $(SYMBOL_FILE_LAG)
OBJECT_FILE_LAG = $(NAME_LAG).o
OUTPUT_ROM_LAG = $(NAME_LAG).gb
SYMBOL_FILE_LAG = $(NAME_LAG).sym
LAG_OBJECTS = $(OBJECT_FILE_LAG) $(OUTPUT_ROM_LAG) $(SYMBOL_FILE_LAG)

MENU_TILEMAP = menu.tilemap
STRINGS = strings.asm
OBJS = $(STD_OBJECTS) $(FRAMES_OBJECTS) $(LAG_OBJECTS) \
	   $(MENU_TILEMAP) $(STRINGS) $(IMAGES)

AS = rgbasm
ASFLAGS = -E
LD = rgblink
FIX = rgbfix
FIXFLAGS = -f gh -p 255 -m "MBC5+RAM+BATTERY"
GFX = rgbgfx
GFXFLAGS = -c embedded
PYTHON = python3

all: $(OUTPUT_ROM_STD) $(OUTPUT_ROM_FRAMES) $(OUTPUT_ROM_LAG)

$(OUTPUT_ROM_LAG): $(OBJECT_FILE_LAG)
	$(LD) $(LDFLAGS_LAG) -o $@ $<
	$(FIX) $(FIXFLAGS) $@

$(OBJECT_FILE_LAG): $(SOURCE_FILE) $(MENU_TILEMAP) $(STRINGS) $(IMAGES)
	$(AS) $(ASFLAGS) $(ASFLAGS_LAG) $< -o $@

$(OUTPUT_ROM_FRAMES): $(OBJECT_FILE_FRAMES)
	$(LD) $(LDFLAGS_FRAMES) -o $@ $<
	$(FIX) $(FIXFLAGS) $@

$(OBJECT_FILE_FRAMES): $(SOURCE_FILE) $(MENU_TILEMAP) $(STRINGS) $(IMAGES)
	$(AS) $(ASFLAGS) $(ASFLAGS_FRAMES) $< -o $@

$(OUTPUT_ROM_STD): $(OBJECT_FILE_STD)
	$(LD) $(LDFLAGS_STD) -o $@ $<
	$(FIX) $(FIXFLAGS) $@

$(OBJECT_FILE_STD): $(SOURCE_FILE) $(MENU_TILEMAP) $(STRINGS) $(IMAGES)
	$(AS) $(ASFLAGS) $(ASFLAGS_STD) $< -o $@

$(MENU_TILEMAP) $(STRINGS): $(GENERATE_MENU) $(MENU_TXT)
	$(PYTHON) $<

$(GFX_DIR)/%.2bpp: $(GFX_DIR)/%.png
	$(GFX) $(GFXFLAGS) -o $@ $<

.PHONY:
clean:
	rm -rf $(OBJS)
